### ISSUE TITLE
Interface unusable in MacOS 10.14 'Mojave' Dark Mode

### ISSUE THREAD

**Issue by JNRuan** [nicklambourne/elan2resource#1]
## Description
With the text and background mismatch, as well as the main menu buttons clashing with dark theme, app is unusable in MacOS's dark mode. User will need to switch to normal mode in order to use Hermes. (See Current Behaviour).

This is a low priority bug, and more a quality of life enhancement.

## Expected Behavior
Hermes GUI standardised to OS themes under default settings.

## Current Behavior
Under MacOS Dark Mode, the interface clashes with white buttons, and text in table is white over a white background.

<img width="762" alt="mainmenu" src="https://user-images.githubusercontent.com/34644792/47633532-029b9f80-db9a-11e8-86b3-dd662b89b694.png">
<img width="762" alt="table1" src="https://user-images.githubusercontent.com/34644792/47633542-05969000-db9a-11e8-91c1-59a15b7a81fd.png">
<img width="762" alt="table2" src="https://user-images.githubusercontent.com/34644792/47633547-07f8ea00-db9a-11e8-9f48-c0f30ec077c3.png">

## Possible Solution
- Font changes
- PyQT Themes
- General Theme Customisation

## Steps to Reproduce
1. Run Hermes, and use as normal under MacOS Dark Mode.

**Comment by JNRuan** [comment]
After further investigation, this seems to be an on-going issue PyQt and MacOS 10.14 Mojave, which is currently being worked on by the PyQt team(s).

[Click for Ongoing updates via qt.io](https://bugreports.qt.io/browse/QTBUG-68891?jql=text%20~%20%22%5C%22dark%20mode%5C%22%20OR%20%5C%22mojave%5C%22%22)

Will leave the issue open until this can be resolved.

Recommend not using Dark Mode when using Hermes, until this is resolved.

**Comment by nicklambourne** [comment]
This appears to have been fixed. The below images are from Mojave 10.14.1 (18B75) in Dark Mode.
<img width="650" alt="screen shot 2018-11-14 at 11 44 04 am" src="https://user-images.githubusercontent.com/9084563/48454350-a45df600-e802-11e8-8846-8c627d163091.png">
<img width="661" alt="screen shot 2018-11-14 at 11 42 52 am" src="https://user-images.githubusercontent.com/9084563/48454309-80021980-e802-11e8-891c-837d80be1862.png">
